---
title: "Consolidate_Data"
output: pdf_document
date: "2025-01-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries, message=FALSE, warning=FALSE}
#install.packages("ggplot2") #install ggplot2
#install.packages("readxl")
#Load in packages
library(dplyr)
library(lubridate)
library(ggplot2)
library(readxl)
library(tidyr)


#set working directory
setwd("N:/MP_Noor")
```

```{r upload files}
#load in all files
wind <- read_excel("../Data/Processed/average_annual_wind_ms.xls")
depth <- read_excel("../Data/Processed/average_depth.xls")
bottom_temp <- read.csv("../Data/Processed/avg_bottom_temp_C.csv")
sediment <- read.csv("../Data/Processed/sediment_results.csv")
seabed <- read.csv("../Data/Processed/seabed_results.csv")

sst_fall <- read.csv("../Data/Processed/sst_fall_summary.csv")
sst_spr <- read.csv("../Data/Processed/sst_spr_summary.csv")
sst_sum <- read.csv("../Data/Processed/sst_sum_summary.csv")
sst_wint <- read.csv("../Data/Processed/sst_wint_summary.csv")

chlor_fall <- read.csv("../Data/Processed/chlor_a_fall_summary.csv")
chlor_spr <- read.csv("../Data/Processed/chlor_a_spr_summary.csv")
chlor_sum <- read.csv("../Data/Processed/chlor_a_sum_summary.csv")
chlor_wint <- read.csv("../Data/Processed/chlor_a_wint_summary.csv")

#sss_fall <- read.csv("../Data/Processed/fall_sss_mean.csv")
#sss_spr <- read.csv("../Data/Processed/spr_sss_mean.csv")
#sss_sum <- read.csv("../Data/Processed/sum_sss_mean.csv")
#sss_wint <- read.csv("../Data/Processed/wint_sss_mean.csv")

sla_fall <- read.csv("../Data/Processed/sla_fall_summary.csv")
sla_spr <- read.csv("../Data/Processed/sla_spr_summary.csv")
sla_sum <- read.csv("../Data/Processed/sla_sum_summary.csv")
sla_wint <- read.csv("../Data/Processed/sla_wint_summary.csv")
```


```{r}
# create list of zonecode names
zone_codes <- c("ASH","EW","NYNJB_North","NYNJB_South","SNE","VW")

#create function to replace current NAMEs to the shortened codes for easier referencing
add_zone_codes <- function(datasets, zone_codes) {
  lapply(datasets, function(df) {
    df <- mutate(df, "ZONE-CODE"= zone_codes)
    df <- df[order(df$`ZONE-CODE`),]
    if ("NAME" %in% names(df)) {
      df <- df[, !names(df) %in% "NAME"]
    }
    return(df)
  })
}

# list of all datasets
datasets <- list(
  sst_fall, sst_spr, sst_sum, sst_wint,
  chlor_fall, chlor_spr, chlor_sum, chlor_wint,
  sla_fall, sla_spr, sla_sum, sla_wint
)

#call function
datasets_with_zone_codes <- add_zone_codes(datasets, zone_codes)

```

```{r}
#extract each dataset separatly
sst_fall <- datasets_with_zone_codes[[1]]
sst_spr <- datasets_with_zone_codes[[2]]
sst_sum <- datasets_with_zone_codes[[3]]
sst_wint <- datasets_with_zone_codes[[4]]
chlor_fall <- datasets_with_zone_codes[[5]]
chlor_spr <- datasets_with_zone_codes[[6]]
chlor_sum <- datasets_with_zone_codes[[7]]
chlor_wint <- datasets_with_zone_codes[[8]]
sla_fall <- datasets_with_zone_codes[[9]]
sla_spr <- datasets_with_zone_codes[[10]]
sla_sum <- datasets_with_zone_codes[[11]]
sla_wint <- datasets_with_zone_codes[[12]]
```

```{r}

# list of dataset names corresponding to datasets
dataset_names <- c(
  "sst_fall", "sst_spr", "sst_sum", "sst_wint",
  "chlor_fall", "chlor_spr", "chlor_sum", "chlor_wint",
  "sla_fall", "sla_spr", "sla_sum", "sla_wint"
)

#list of datasets
datasets <- list(
  sst_fall, sst_spr, sst_sum, sst_wint,
  chlor_fall, chlor_spr, chlor_sum, chlor_wint,
  sla_fall, sla_spr, sla_sum, sla_wint
)

# function to add the dataset name to each column
rename_cols <- function(datasets, dataset_names) {
  datasets <- mapply(function(df, name) {
    df <- df %>%
      select(4:5,8)
    col_to_rename <- grep("mean$", names(df), value = TRUE)  # Find columns ending in "mean"
    
    if (length(col_to_rename) > 0) {
      new_names <- paste0(col_to_rename, "_", name)  # Append dataset name to column name
      names(df)[names(df) %in% col_to_rename] <- new_names  # Rename columns
    }
    
    return(df)
  }, datasets, dataset_names, SIMPLIFY = FALSE)  # Ensure output is a list
  
  return(datasets)
}

# call function
datasets <- rename_cols(datasets, dataset_names)

# extract each individual dataset
sst_fall <- datasets[[1]]
sst_spr <- datasets[[2]]
sst_sum <- datasets[[3]]
sst_wint <- datasets[[4]]
chlor_fall <- datasets[[5]]
chlor_spr <- datasets[[6]]
chlor_sum <- datasets[[7]]
chlor_wint <- datasets[[8]]
sla_fall <- datasets[[9]]
sla_spr <- datasets[[10]]
sla_sum <- datasets[[11]]
sla_wint <- datasets[[12]]
```

```{r}
# list of zone-codes
sedsea_new_names <- c("ASH", "EW", "NYNJB_North", "NYNJB_South", "SNE", "VW")

# reformat
sediment <- sediment %>%
  select(2:9) %>% #select out necessary columns
  rename(`ZONE-CODE` = ZONE.CODE) %>% #rename zone code col to match others
  mutate(`ZONE-CODE` = sedsea_new_names) # fill in the zone code col with sedsea_new_names

#reformat
seabed <- seabed %>%
  select(2:9) %>% #select out necessary columns
  rename(`ZONE-CODE` = ZONE.CODE) %>% #rename zone code col to match others
  mutate(`ZONE-CODE` = sedsea_new_names) # fill in the zone code col with sedsea_new_names

#the zones were in a different order in this df
zonecodes_temp <- c("VW", "EW", "ASH", "SNE", "NYNJB_North", "NYNJB_South")
bottom_temp <- bottom_temp %>%
  mutate('ZONE_CODE' = zonecodes_temp) %>%
  select(`ZONE_CODE`, MEAN) %>%
  rename(`ZONE-CODE` = ZONE_CODE, Mean_Bottom_Temp = MEAN) %>%
  arrange(`ZONE-CODE`)

# reformat all dfs to have same `ZONE-CODE` for joining and make sure to arrange by zone-code
depth <- depth %>%
  rename(Mean_Depth = MEAN) %>%
  mutate(`ZONE-CODE` = zonecodes_temp) %>%
  select(`ZONE-CODE`, Mean_Depth) %>%
  arrange(`ZONE-CODE`)

wind <- wind %>%
  rename(Mean_Wind_Speed = MEAN) %>%
  mutate(`ZONE-CODE` = zonecodes_temp) %>%
  select(`ZONE-CODE`, Mean_Wind_Speed) %>%
  arrange(`ZONE-CODE`)

```

```{r join_data}
#Join data
joined_dfs <- depth %>%
  full_join(wind, by="ZONE-CODE") %>%
  full_join(sediment, by="ZONE-CODE") %>%
  full_join(seabed, by="ZONE-CODE") %>%
  full_join(bottom_temp, by="ZONE-CODE") %>%
  full_join(sst_fall, by="ZONE-CODE") %>%
  full_join(sst_spr, by="ZONE-CODE") %>%
  full_join(sst_sum, by="ZONE-CODE") %>%
  full_join(sst_wint, by="ZONE-CODE") %>%
  full_join(chlor_fall, by="ZONE-CODE") %>%
  full_join(chlor_spr, by="ZONE-CODE") %>%
  full_join(chlor_sum, by="ZONE-CODE") %>%
  full_join(chlor_wint, by="ZONE-CODE") %>%
  full_join(sla_fall, by="ZONE-CODE") %>%
  full_join(sla_spr, by="ZONE-CODE") %>%
  full_join(sla_sum, by="ZONE-CODE") %>%
  full_join(sla_wint, by="ZONE-CODE")

```

```{r}
joined_dfs[is.na(joined_dfs)] <- 0.0001 #make all NA's into 0.0001
joined_dfs[joined_dfs == 0] <- 0.0001 #make all 0's into 0.0001
#rename col for analysis in arcgis
#joined_dfs <- joined_dfs %>%
  #rename(NAME = `ZONE-CODE`)
```

```{r}
# save as csv file
write.csv(scaled_data, file = "N:/MP_Noor/Data/Processed/Joined_MODIS.csv")
```

```{r}
NAME <- c("Atlantic Shores South", "Empire Wind", "NYNJB North", "NYNJB South", "Southern New England", "Vineyard Wind 1 Offshore Wind Project")
just_benthic <- sediment %>%
  full_join(seabed, by="ZONE-CODE") %>%
  mutate(`ZONE-CODE` = NAME) %>%
  rename(NAME = `ZONE-CODE`)

just_benthic[is.na(just_benthic)] <- 0.0001 #make all NA's into 0.0001
just_benthic[just_benthic == 0] <- 0.0001 #make all 0's into 0.0001
```

```{r}
# save as csv file
write.csv(just_benthic, file = "N:/MP_Noor/Data/Processed/Joined_just_benth.csv")
```

```{r}
just_oceano <- depth %>%
  full_join(wind, by="ZONE-CODE") %>%
  full_join(bottom_temp, by="ZONE-CODE") %>%
  full_join(sst_fall, by="ZONE-CODE") %>%
  full_join(sst_spr, by="ZONE-CODE") %>%
  full_join(sst_sum, by="ZONE-CODE") %>%
  full_join(sst_wint, by="ZONE-CODE") %>%
  full_join(chlor_fall, by="ZONE-CODE") %>%
  full_join(chlor_spr, by="ZONE-CODE") %>%
  full_join(chlor_sum, by="ZONE-CODE") %>%
  full_join(chlor_wint, by="ZONE-CODE") %>%
  full_join(sla_fall, by="ZONE-CODE") %>%
  full_join(sla_spr, by="ZONE-CODE") %>%
  full_join(sla_sum, by="ZONE-CODE") %>%
  full_join(sla_wint, by="ZONE-CODE") %>%
  mutate(`ZONE-CODE` = NAME) %>%
  rename(NAME = `ZONE-CODE`)

just_oceano[is.na(just_oceano)] <- 0.0001 #make all NA's into 0.0001
just_oceano[just_oceano == 0] <- 0.0001 #make all 0's into 0.0001
```

```{r}
# save as csv file
write.csv(just_oceano, file = "N:/MP_Noor/Data/Processed/Joined_just_oceano.csv")
```

```{r}
# create zone code mapping
zone_code_mapping <- joined_dfs$`ZONE-CODE`
# make zonecode numeric
joined_dfs$`ZONE-CODE` <- as.numeric(as.factor(joined_dfs$`ZONE-CODE`))
#head(joined_dfs)
```


```{r separate out the sites and regions}
#lists of site and region abbvs to separate out and compare separately
site_abbv <- c("ASH", "EW", "VW")
region_abbv <- c("NYNJB_North", "NYNJB_South", "SNE")

#filter out by site and region
only_sites <- filter(joined_dfs, `ZONE-CODE` %in% site_abbv)
only_regions <- filter(joined_dfs, `ZONE-CODE` %in% region_abbv)

#Create zone code mapping
site_zone_mapping <- only_sites$`ZONE-CODE`
region_zone_mapping <- only_regions$`ZONE-CODE`

#make zonecodes numeric
only_sites$`ZONE-CODE`<- as.numeric(as.factor(only_sites$`ZONE-CODE`))
only_regions$`ZONE-CODE`<- as.numeric(as.factor(only_regions$`ZONE-CODE`))
```

```{r scale all dataframes}
#scale each df
scaled_data <- as.data.frame(scale(joined_dfs))
#head(scaled_data)
scaled_sites <- as.data.frame(scale(only_sites))
#head(scaled_sites)
scaled_regions <- as.data.frame(scale(only_regions))
#head(scaled_regions)
```

```{r}
#reinsert zone code mapping for labeling
scaled_data$`ZONE-CODE` <- zone_code_mapping

#compute pairwise euclidean distance b/w zones
euc_dist <- dist(scaled_data, method = "euclidean")

#see which sites are most similar to each other in distance matrix alone
dist_matrix <- euc_dist %>%
  as.matrix() %>%
  as_tibble(rownames = "A") %>%
  pivot_longer(-A ,names_to = "B", values_to = "distances")

#reinsert zone code mapping for labeling
dist_matrix$A <- zone_code_mapping[as.numeric(dist_matrix$A)]
dist_matrix$B <- zone_code_mapping[as.numeric(dist_matrix$B)]

# View updated distance matrix w/correct labels
#head(dist_matrix)

#plot matrix
ggplot(dist_matrix, aes(x = A, y = B, fill = distances)) +
  geom_tile() +
  scale_fill_gradient(low = "#FF0000", high = "#FFFFFF", name = NULL) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(x = "", y = "")

```

```{r}
# save as png
ggsave(filename = "N:/MP_Noor/Data/Figures/dist_matrix_all.png", height = 5, width = 6, dpi = 300)
```

```{r}
#reinsert zone code mapping for labeling
scaled_sites$`ZONE-CODE` <- site_zone_mapping

#compute pairwise euclidean distance b/w zones
site_euc_dist <- dist(scaled_sites, method = "euclidean")

#see which sites are most similar to each other in distance matrix alone
site_dist_matrix <- site_euc_dist %>%
  as.matrix() %>%
  as_tibble(rownames = "A") %>%
  pivot_longer(-A ,names_to = "B", values_to = "distances")

#reinsert zone code mapping for labeling
site_dist_matrix$A <- site_zone_mapping[as.numeric(site_dist_matrix$A)]
site_dist_matrix$B <- site_zone_mapping[as.numeric(site_dist_matrix$B)]

# View the updated distance matrix with correct labels
#head(site_dist_matrix)

#Plot matrix
ggplot(site_dist_matrix, aes(x = A, y = B, fill = distances)) +
  geom_tile() +
  scale_fill_gradient(low = "#FF0000", high = "#FFFFFF", name = NULL) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(x = "", y = "")
```

```{r}
# save as png
ggsave(filename = "N:/MP_Noor/Data/Figures/dist_matrix_sites.png", height = 5, width = 6, dpi = 300)
```

```{r}
#reinsert zone code mapping for labeling
scaled_regions$`ZONE-CODE` <- region_zone_mapping

#compute pairwise euclidean distance b/w zones
region_euc_dist <- dist(scaled_regions, method = "euclidean")

#see which sites are most similar to each other in distance matrix alone
region_dist_matrix <- region_euc_dist %>%
  as.matrix() %>%
  as_tibble(rownames = "A") %>%
  pivot_longer(-A ,names_to = "B", values_to = "distances")

#reinsert zone code mapping for labeling
region_dist_matrix$A <- region_zone_mapping[as.numeric(region_dist_matrix$A)]
region_dist_matrix$B <- region_zone_mapping[as.numeric(region_dist_matrix$B)]

# View the updated distance matrix with correct labels
head(region_dist_matrix)

# plot matrix
ggplot(region_dist_matrix, aes(x = A, y = B, fill = distances)) +
  geom_tile() +
  scale_fill_gradient(low = "#FF0000", high = "#FFFFFF", name = NULL) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(x = "", y = "")
```

```{r}
#save as png
ggsave(filename = "N:/MP_Noor/Data/Figures/dist_matrix_regions.png", height = 5, width = 6, dpi = 300)
```

```{r}
# define seasons and variable prefixes
seasons <- c("FALL", "SPRING", "SUMMER", "WINTER")
names_datasets <- c("fall", "spr", "sum", "wint") # Ensure lowercase for dataset names
variables <- c("sst", "chlor", "sla")
rename_suffixes <- c("mean_sst", "mean_chlor_a", "mean_sla")

# make empty list to store results
results <- list()

# Loop over each variable and season
for (i in seq_along(variables)) {
  for (j in seq_along(seasons)) {
    # make the dataset name dynamically
    dataset_name <- paste0(variables[i], "_", names_datasets[j])
    # Check if the dataset exists
    if (exists(dataset_name)) {
      # make the new variable name for renaming
      rename_col <- rename_suffixes[i]
      # apply transformations
      results[[dataset_name]] <- get(dataset_name) %>%
        mutate(SEASON = seasons[j]) %>%
        rename(!!paste0("MEAN_", toupper(variables[i])) := !!sym(paste0(rename_col, "_", names_datasets[j])))
    }
  }
}

```

```{r}
#extract out each dataset separately
sst_fall <- results[["sst_fall"]]
sst_spr <- results[["sst_spr"]]
sst_sum <- results[["sst_sum"]]
sst_wint <- results[["sst_wint"]]

chlor_fall <- results[["chlor_fall"]]
chlor_spr <- results[["chlor_spr"]]
chlor_sum <- results[["chlor_sum"]]
chlor_wint <- results[["chlor_wint"]]

sla_fall <- results[["sla_fall"]]
sla_spr <- results[["sla_spr"]]
sla_sum <- results[["sla_sum"]]
sla_wint <- results[["sla_wint"]]
```


```{r}
#bind datasets by variable
all_sst <- rbind(sst_fall,sst_spr,sst_sum,sst_wint) %>%
  group_by(`ZONE-CODE`) %>%
  summarise(MEAN_SST= mean(MEAN_SST))

all_chlor <- rbind(chlor_fall,chlor_spr,chlor_sum,chlor_wint) %>%
  group_by(`ZONE-CODE`) %>%
  summarise(MEAN_CHLOR= mean(MEAN_CHLOR))

all_sla <- rbind(sla_fall,sla_spr,sla_sum,sla_wint) %>%
  group_by(`ZONE-CODE`) %>%
  summarise(MEAN_SLA= mean(MEAN_SLA))
```

```{r annual plots}
#plot sst
sst_plot <- all_sst %>%
  ggplot(aes(x=`ZONE-CODE`,y=MEAN_SST, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Annual SST In Celcius") +
  coord_cartesian(ylim = c(10,20))

sst_plot #show plot

#save as png
ggsave(filename = "N:/MP_Noor/Data/Figures/annual_sst.png", height = 4, width = 6, dpi = 300)

#plot chlor
chlor_plot <- all_chlor %>%
  ggplot(aes(x=`ZONE-CODE`,y=MEAN_CHLOR, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Annual CHLOR_A")

chlor_plot #call plot

#save as png
ggsave(filename = "N:/MP_Noor/Data/Figures/annual_chlor.png", height = 4, width = 6, dpi = 300)

#plot sla
sla_plot <- all_sla %>%
  ggplot(aes(x=`ZONE-CODE`,y=MEAN_SLA, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Annual SLA")

sla_plot #show plot

#save as png
ggsave(filename = "N:/MP_Noor/Data/Figures/annual_sla.png", height = 4, width = 6, dpi = 300)
```

```{r seasonal sst plots}
# plot each variable by season instead of annual and save as png files
fall_sst_plot <- sst_fall %>%
  ggplot(aes(x=`ZONE-CODE`,y=MEAN_SST, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Fall SST") +
  coord_cartesian(ylim = c(15,20))

fall_sst_plot

ggsave(filename = "N:/MP_Noor/Data/Figures/fall_sst.png", height = 4, width = 6, dpi = 300)

spr_sst_plot <- sst_spr %>%
  ggplot(aes(x=`ZONE-CODE`,y=MEAN_SST, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Spring SST") +
  coord_cartesian(ylim = c(7,10))

spr_sst_plot

ggsave(filename = "N:/MP_Noor/Data/Figures/spr_sst.png", height = 4, width = 6, dpi = 300)

sum_sst_plot <- sst_sum %>%
  ggplot(aes(x=`ZONE-CODE`,y=MEAN_SST, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Summer SST") +
  coord_cartesian(ylim = c(15,25))

sum_sst_plot

ggsave(filename = "N:/MP_Noor/Data/Figures/sum_sst.png", height = 4, width = 6, dpi = 300)

wint_sst_plot <- sst_wint %>%
  ggplot(aes(x=`ZONE-CODE`,y=MEAN_SST, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Winter SST") +
  coord_cartesian(ylim = c(7,10))

wint_sst_plot

ggsave(filename = "N:/MP_Noor/Data/Figures/wint_sst.png", height = 4, width = 6, dpi = 300)
```

```{r seasonal chlor_a plots}
# plot each variable by season instead of annual and save as png files
fall_chlor_plot <- chlor_fall %>%
  ggplot(aes(x=`ZONE-CODE`,y=MEAN_CHLOR, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Fall Chlorophyll A Levels")

fall_chlor_plot

ggsave(filename = "N:/MP_Noor/Data/Figures/fall_chlor.png", height = 4, width = 6, dpi = 300)

spr_chlor_plot <- chlor_spr %>%
  ggplot(aes(x=`ZONE-CODE`,y=MEAN_CHLOR, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Spring Chlorophyll A Levels")

spr_chlor_plot

ggsave(filename = "N:/MP_Noor/Data/Figures/spr_chlor.png", height = 4, width = 6, dpi = 300)

sum_chlor_plot <- chlor_sum %>%
  ggplot(aes(x=`ZONE-CODE`,y=MEAN_CHLOR, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Summer Chlorophyll A Levels")

sum_chlor_plot

ggsave(filename = "N:/MP_Noor/Data/Figures/sum_chlor.png", height = 4, width = 6, dpi = 300)

wint_chlor_plot <- chlor_wint %>%
  ggplot(aes(x=`ZONE-CODE`,y=MEAN_CHLOR, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Winter Chlorophyll A Levels")

wint_chlor_plot

ggsave(filename = "N:/MP_Noor/Data/Figures/wint_chlor.png", height = 4, width = 6, dpi = 300)
```

```{r seasonal sla plots}
# plot each variable by season instead of annual and save as png files
fall_sla_plot <- sla_fall %>%
  ggplot(aes(x=`ZONE-CODE`,y=MEAN_SLA, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Fall SLA") +
  coord_cartesian(ylim = c(0.10,0.15))

fall_sla_plot

ggsave(filename = "N:/MP_Noor/Data/Figures/fall_sla.png", height = 4, width = 6, dpi = 300)

spr_sla_plot <- sla_spr %>%
  ggplot(aes(x=`ZONE-CODE`,y=MEAN_SLA, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Spring SLA")

spr_sla_plot

ggsave(filename = "N:/MP_Noor/Data/Figures/spr_sla.png", height = 4, width = 6, dpi = 300)

sum_sla_plot <- sla_sum %>%
  ggplot(aes(x=`ZONE-CODE`,y=MEAN_SLA, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Summer SLA")

sum_sla_plot

ggsave(filename = "N:/MP_Noor/Data/Figures/sum_sla.png", height = 4, width = 6, dpi = 300)

wint_sla_plot <- sla_wint %>%
  ggplot(aes(x=`ZONE-CODE`,y=MEAN_SLA, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Winter SLA")

wint_sla_plot

ggsave(filename = "N:/MP_Noor/Data/Figures/wint_sla.png", height = 4, width = 6, dpi = 300)
```

```{r}
# plot each variable and save as png files
wind_plot <- wind %>%
  ggplot(aes(x=`ZONE-CODE`, y=Mean_Wind_Speed, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Wind Speeds") +
  coord_cartesian(ylim = c(8.5, 9.5))

wind_plot

ggsave(filename = "N:/MP_Noor/Data/Figures/avg_wind.png", height = 4, width = 6, dpi = 300)

depth_plot <- depth %>%
  ggplot(aes(x=`ZONE-CODE`, y=Mean_Depth, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title="Average Depth")

depth_plot

ggsave(filename = "N:/MP_Noor/Data/Figures/avg_depth.png", height = 4, width = 6, dpi = 300)

bottom_temp_plot <- bottom_temp %>%
  ggplot(aes(x=`ZONE-CODE`, y=Mean_Bottom_Temp, fill = `ZONE-CODE`)) +
  geom_col() +
  labs(title = "Average Bottom Temperatures") +
  coord_cartesian(ylim = c(9,12))

bottom_temp_plot

ggsave(filename = "N:/MP_Noor/Data/Figures/avg_bottom_temp.png", height = 4, width = 6, dpi = 300)
  
```

```{r scratch}
# Function to rename the "mean_*" columns based on the season
rename_columns <- function(datasets, dataset_names) {
  # Extract seasons from dataset names (e.g., "sst_fall" -> "fall")
  seasons <- sub(".*_(fall|spr|sum|wint)$", "\\1", dataset_names)
  
  # Rename columns dynamically
  datasets <- mapply(function(df, name, season) {
    # Determine the column to rename based on the dataset type
    if (grepl("^chlor_", name)) {
      col_to_rename <- "mean_chlor_a"
    } else {
      col_to_rename <- grep("^mean_", names(df), value = TRUE)
    }
    
    # Rename the column if found
    if (length(col_to_rename) > 0 && col_to_rename %in% names(df)) {
      new_name <- paste0(col_to_rename, "_", season) # Append season to column name
      names(df)[names(df) == col_to_rename] <- new_name
    }
    return(df)
  }, datasets, dataset_names, seasons, SIMPLIFY = FALSE)
  
  return(datasets)
}

# List of dataset names corresponding to datasets
dataset_names <- c(
  "sst_fall", "sst_spr", "sst_sum", "sst_wint",
  "chlor_fall", "chlor_spr", "chlor_sum", "chlor_wint",
  "sla_fall", "sla_spr", "sla_sum", "sla_wint"
)

# List of datasets
datasets <- list(
  sst_fall, sst_spr, sst_sum, sst_wint,
  chlor_fall, chlor_spr, chlor_sum, chlor_wint,
  sla_fall, sla_spr, sla_sum, sla_wint
)

# Apply the renaming function
datasets_with_renamed_columns <- rename_columns(datasets, dataset_names)

# Optionally, extract individual datasets if needed
sst_fall <- datasets_with_renamed_columns[[1]]
sst_spr <- datasets_with_renamed_columns[[2]]
sst_sum <- datasets_with_renamed_columns[[3]]
sst_wint <- datasets_with_renamed_columns[[4]]
chlor_fall <- datasets_with_renamed_columns[[5]]
chlor_spr <- datasets_with_renamed_columns[[6]]
chlor_sum <- datasets_with_renamed_columns[[7]]
chlor_wint <- datasets_with_renamed_columns[[8]]
sla_fall <- datasets_with_renamed_columns[[9]]
sla_spr <- datasets_with_renamed_columns[[10]]
sla_sum <- datasets_with_renamed_columns[[11]]
sla_wint <- datasets_with_renamed_columns[[12]]

```