---
title: "Seabed_Results_All_Sites"
output: pdf_document
date: "2025-02-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries, message=FALSE, warning=FALSE}
#Load in packages
library(dplyr)
library(lubridate)
library(ggplot2)
library(readxl)
library(tidyr)
library(forcats)
library(gridExtra)

setwd("N:/MP_Noor") #set working directory
```

```{r bring in files}
#load in excel files
ocs0486 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0486set.xls")
ocs0487 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0487set.xls")
ocs0498 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0498set.xls")
ocs0499 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0499set.xls")
ocs0500 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0500set.xls")
ocs0501 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0501set.xls")
ocs0512 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0512set.xls")
ocs0517 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0517set.xls")
ocs0520 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0520set.xls")
ocs0521 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0521set.xls")
ocs0522 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0522set.xls")
ocs0532 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0532set.xls")
ocs0537 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0537set.xls")
ocs0538 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0538set.xls")
ocs0539 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0539set.xls")
ocs0541 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0541set.xls")
ocs0542 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0542set.xls")
ocs0544 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0544set.xls")
ocs0549 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0549set.xls")
ocs0534 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0534set.xls")
ocs0561 <- read_excel("N:/MP_Noor/Data/Processed/ocs-a_0561set.xls")
```

```{r format ash}
# create list of seabed form names corresponding to the VALUE col in each dataset
seabedforms <- c("Depression", "Mid Flat", "Upper Flat", "Low Slope", "Scarp", "Side Slope", "Upper Slope")

# reformat to replace values to corresponding seabed forms
ocs0486 <- ocs0486 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) # calculate percent area covered

# order the seabed forms correctly for plotting
ocs0486$SEABED <- forcats::fct_inorder(ocs0486$SEABED)
```

```{r}
# reformat to replace values to corresponding seabed forms for all ocs datasets

ocs0487 <- ocs0487 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0498 <- ocs0498 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0499 <- ocs0499 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0500 <- ocs0500 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0501 <- ocs0501 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0512 <- ocs0512 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0517 <- ocs0517 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0520 <- ocs0520 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0521 <- ocs0521 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0522 <- ocs0522 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0532 <- ocs0532 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0537 <- ocs0537 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0538 <- ocs0538 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0539 <- ocs0539 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0541 <- ocs0541 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0542 <- ocs0542 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0544 <- ocs0544 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0549 <- ocs0549 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0534 <- ocs0534 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

ocs0561 <- ocs0561 %>%
  mutate(VALUE = seabedforms) %>%
  rename(SEABED = VALUE) %>%
  mutate(PERCENT = (COUNT/sum(COUNT))*100) %>%
  mutate(SEABED = forcats::fct_inorder(SEABED))

```

```{r}
# create list of dataset names corresponding to the datasets
dataset_names <- c("ocs0486", "ocs0487", "ocs0498", "ocs0499", "ocs0500", 
                   "ocs0501", "ocs0512", "ocs0517", "ocs0520", "ocs0521", 
                   "ocs0522", "ocs0532", "ocs0534", "ocs0537", "ocs0538", 
                   "ocs0539", "ocs0541", "ocs0542", "ocs0544", "ocs0549", 
                   "ocs0561")
# list of datasets
datasets <- list(ocs0486, ocs0487, ocs0498, ocs0499, ocs0500, ocs0501, ocs0512, 
                 ocs0517, ocs0520, ocs0521, ocs0522, ocs0532, ocs0534, ocs0537,
                 ocs0538, ocs0539, ocs0541, ocs0542, ocs0544, ocs0549, ocs0561 
                 )

# create function to add column and populate it with the appropriate dataset name
create_column <- function(datasets, dataset_names) {
  lapply(seq_along(datasets), function(i) {
    df <- datasets[[i]]
    # Use the name from dataset_names corresponding to the index `i`
    df <- df %>% mutate("ZONE-CODE" = dataset_names[i])
    return(df)
  })
}

# call function
new_datasets <- create_column(datasets, dataset_names)

# extract out each dataset separately
ocs0486 <- new_datasets[[1]]
ocs0487 <- new_datasets[[2]]
ocs0498 <- new_datasets[[3]]
ocs0499 <- new_datasets[[4]]
ocs0500 <- new_datasets[[5]]
ocs0501 <- new_datasets[[6]]
ocs0512 <- new_datasets[[7]]
ocs0517 <- new_datasets[[8]]
ocs0520 <- new_datasets[[9]]
ocs0521 <- new_datasets[[10]]
ocs0522 <- new_datasets[[11]]
ocs0532 <- new_datasets[[12]]
ocs0534 <- new_datasets[[13]]
ocs0537 <- new_datasets[[14]]
ocs0538 <- new_datasets[[15]]
ocs0539 <- new_datasets[[16]]
ocs0541 <- new_datasets[[17]]
ocs0542 <- new_datasets[[18]]
ocs0544 <- new_datasets[[19]]
ocs0549 <- new_datasets[[20]]
ocs0561 <- new_datasets[[21]]

```

```{r}
# list of datasets
datasets <- list(ocs0486, ocs0487, ocs0498, ocs0499, ocs0500, ocs0501, ocs0512, 
                 ocs0517, ocs0520, ocs0521, ocs0522, ocs0532, ocs0534, ocs0537,
                 ocs0538, ocs0539, ocs0541, ocs0542, ocs0544, ocs0549, ocs0561 
                 )

## create function to select out columns 1, 3, and 4 and then pivot table
pivoted <- function(datasets) {
  lapply(datasets, function(df) {
    df <- df %>%
      select(1,3,4) %>%
      pivot_wider(names_from = SEABED, values_from = PERCENT)
    df[,1] <- toupper(df[,1]) #make all text in first column uppercase
    return(df)
  })
  
  
}

# call function
pivoted_data <- pivoted(datasets)

# extract out each dataset separately
ocs0486 <- pivoted_data[[1]]
ocs0487 <- pivoted_data[[2]]
ocs0498 <- pivoted_data[[3]]
ocs0499 <- pivoted_data[[4]]
ocs0500 <- pivoted_data[[5]]
ocs0501 <- pivoted_data[[6]]
ocs0512 <- pivoted_data[[7]]
ocs0517 <- pivoted_data[[8]]
ocs0520 <- pivoted_data[[9]]
ocs0521 <- pivoted_data[[10]]
ocs0522 <- pivoted_data[[11]]
ocs0532 <- pivoted_data[[12]]
ocs0534 <- pivoted_data[[13]]
ocs0537 <- pivoted_data[[14]]
ocs0538 <- pivoted_data[[15]]
ocs0539 <- pivoted_data[[16]]
ocs0541 <- pivoted_data[[17]]
ocs0542 <- pivoted_data[[18]]
ocs0544 <- pivoted_data[[19]]
ocs0549 <- pivoted_data[[20]]
ocs0561 <- pivoted_data[[21]]
```

```{r}
# join all dfs
joined_df <- rbind(ocs0486, ocs0487, ocs0498, ocs0499, ocs0500, ocs0501, ocs0512, 
                 ocs0517, ocs0520, ocs0521, ocs0522, ocs0532, ocs0534, ocs0537,
                 ocs0538, ocs0539, ocs0541, ocs0542, ocs0544, ocs0549, ocs0561 
                 )
```

```{r}
#save df as csv
write.csv(joined_df, file = "N:/MP_Noor/Data/Processed/seabed_results_all_sites.csv")
```

